/*

 MAP_EVERGREEN_TOWN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 128 x 64
   Tile set      : ..\tiles\Outdoors.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Map_EvergreenTownWidth 128
#define Map_EvergreenTownHeight 64
#define Map_EvergreenTownBank 0

#define Map_EvergreenTown Map_EvergreenTownPLN0
extern unsigned const char Map_EvergreenTownPLN0[];
extern unsigned const char Map_EvergreenTownPLN1[];

/* End of MAP_EVERGREEN_TOWN.H */
